Trigger ADO Pipeline from GH Actions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,8 +20,6 @@ permissions:
 jobs:
   create-infra:
     runs-on: ubuntu-latest
-    # Selects 'test' for -rc tags, 'prod' for regular tags, or branch name otherwise
-    environment: ${{ github.ref_type != 'tag' && github.ref_name || contains(github.ref, '-rc') && 'test' || 'prod' }}
     
     defaults:
       run:
@@ -38,6 +36,51 @@ jobs:
         tenant-id: ${{ secrets.AZURE_MI_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_MI_SUBSCRIPTION_ID }}
     
+    - name: Trigger Azure Pipeline
+      id: trigger_pipeline
+      run: |
+        ADO_TOKEN=$(az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" -o tsv)
+        export AZURE_DEVOPS_EXT_PAT=$ADO_TOKEN
+        RUN_ID=$(az pipelines run \
+          --id "1" \
+          --org "${{ secrets.AZURE_ADO_ORG_URL }}" \
+          --project "${{ secrets.AZURE_ADO_PROJECT }}" \
+          --branch "${{ github.ref }}" \
+          --commit-id ${{ github.sha }} \
+          --query "id" -o tsv)
+
+        echo "Waiting for Azure DevOps Pipeline run to complete..."
+        while true; do
+          PIPELINE_STATUS=$(az pipelines runs show \
+            --id $RUN_ID \
+            --org "${{ secrets.AZURE_ADO_ORG_URL }}" \
+            --project "${{ secrets.AZURE_ADO_PROJECT }}" \
+            --query "status" -o tsv)
+
+          echo "Current pipeline status: $PIPELINE_STATUS"
+
+          if [[ "$PIPELINE_STATUS" == "completed" ]]; then
+            PIPELINE_RESULT=$(az pipelines runs show \
+              --id $RUN_ID \
+              --org "${{ secrets.AZURE_ADO_ORG_URL }}" \
+              --project "${{ secrets.AZURE_ADO_PROJECT }}" \
+              --query "result" -o tsv)
+
+            echo "Pipeline completed with result: $PIPELINE_RESULT"
+            if [[ "$PIPELINE_RESULT" == "succeeded" ]]; then
+              exit 0
+            else
+              echo "Azure DevOps Pipeline failed with result: $PIPELINE_RESULT"
+              exit 1
+            fi
+          elif [[ "$PIPELINE_STATUS" == "cancelling" || "$PIPELINE_STATUS" == "notStarted" || "$PIPELINE_STATUS" == "inProgress" ]]; then
+            sleep 10
+          else
+            echo "Azure DevOps Pipeline finished with unexpected status: $PIPELINE_STATUS"
+            exit 1
+          fi
+        done
+
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
 
